steps:
  - id: bootstrap-builder
    name: docker:22.06-rc-cli
    env:
      - "DOCKER_BUILDKIT=1"
      - "DOCKER_CLI_EXPERIMENTAL=enabled"
    entrypoint: "docker"
    args:
      - buildx
      - create
      - --name=buildkitd 
      - --node=buildkitd
      - --bootstrap
      - --buildkitd-flags='--containerd-worker-snapshotter=stargz'
      - --driver=docker-container
      - --platform=linux/amd64,linux/arm64
      - --driver-opt=image=moby/buildkit:master
      - --use
    waitFor:
      - "-"

  - id: cloud-pubsub-emulator
    name: docker:22.06-rc-cli
    env:
      - "DOCKER_BUILDKIT=1"
      - "DOCKER_CLI_EXPERIMENTAL=enabled"
    entrypoint: "docker"
    args:
      - buildx
      - build
      - --platform=linux/amd64,linux/arm64
      - --pull
      - --build-arg=BUILDKIT_INLINE_CACHE=1
      - --build-arg=BUILDKIT_INLINE_BUILDINFO_ATTRS=1
      - --cache-from=type=registry,ref=debian:bullseye-slim
      - --build-arg=PUBSUB_EMULATOR_BUILD_NUMBER=${_PUBSUB_EMULATOR_BUILD_NUMBER}
      - --label=org.opencontainers.image.revision=${COMMIT_SHA}
      - --output=type=registry
      - --target=cloud-pubsub-emulator
      - --tag=asia-docker.pkg.dev/${PROJECT_ID}/gcp/cloud-pubsub-emulator:${_PUBSUB_EMULATOR_BUILD_NUMBER}
      - --tag=us-docker.pkg.dev/${PROJECT_ID}/gcp/cloud-pubsub-emulator:${_PUBSUB_EMULATOR_BUILD_NUMBER}
      - .

substitutions:
  _PUBSUB_EMULATOR_BUILD_NUMBER: "20230120151534"

tags:
  - "gcp.cloud-pubsub-emulator"

options:
  dynamic_substitutions: true
  requestedVerifyOption: 'VERIFIED'

timeout: 900s  # 15min
